"""Read-only interface to MSVC IntelliSense Browse.VC.db (SQLite).

Browse.VC.db is generated by Visual Studio / VSCode cpptools during
compilation.  It contains full symbol information — definitions, members,
inheritance — indexed and queryable in ~1-3 ms even on codebases with
millions of symbols.

This module provides an *optional* acceleration layer.  When the database
is not found, unavailable, or has an unexpected schema, every method
returns empty results and the caller should fall back to other search
strategies.
"""

from __future__ import annotations

import logging
import sqlite3
from pathlib import Path

logger = logging.getLogger(__name__)

# ── Code‑item kind IDs that represent navigable definitions ──────────────
# Subset of the 64 kinds in VS 2022 v17+; used as the default filter in
# :meth:`BrowseDBProvider.find_symbol`.
NAVIGABLE_KINDS: tuple[int, ...] = (
    1,  # class
    2,  # struct
    3,  # union
    4,  # enum
    5,  # interface
    6,  # member_function
    7,  # member
    8,  # enumerator
    10,  # template
    16,  # concept
    18,  # namespace
    20,  # using_alias
    21,  # typedef
    27,  # function
    28,  # variable
    37,  # macro_define
)


# ── Auto‑discovery ───────────────────────────────────────────────────────


def discover_browse_dbs(repo_path: Path, *, max_parents: int = 4) -> list[Path]:
    """Find Browse.VC.db files near *repo_path*.

    Searches ``.vs/*/v*/Browse.VC.db`` starting at *repo_path* and walking
    up to *max_parents* ancestor directories.  Results are sorted newest
    first (by mtime).
    """
    candidates: list[Path] = []
    dirs_to_check = [repo_path] + list(repo_path.parents)[:max_parents]
    for d in dirs_to_check:
        vs_dir = d / ".vs"
        if not vs_dir.is_dir():
            continue
        for db in vs_dir.glob("*/v*/Browse.VC.db"):
            if db.is_file():
                candidates.append(db)
        # Also check Insiders location
        for db in vs_dir.glob("*/v*/Insiders/Browse.VC.db"):
            if db.is_file():
                candidates.append(db)
    # Newest first
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates


# ── Provider ─────────────────────────────────────────────────────────────


class BrowseDBProvider:
    """Read-only query interface to a single Browse.VC.db file.

    Opens the database in **read-only** mode to avoid locking conflicts
    with a running Visual Studio instance.  If the file is missing, locked,
    corrupt, or has an unrecognised schema, the provider enters *degraded*
    mode where all queries return empty results.  Check :pyattr:`available`.
    """

    def __init__(self, db_path: Path):
        self._db_path = db_path
        self._conn: sqlite3.Connection | None = None
        self._available = False
        self._kind_map: dict[int, str] = {}

        try:
            self._conn = sqlite3.connect(
                f"file:{db_path}?mode=ro",
                uri=True,
                timeout=5,
                check_same_thread=False,
            )
            # Verify expected tables exist
            tables = {
                r[0]
                for r in self._conn.execute(
                    "SELECT name FROM sqlite_master WHERE type='table'"
                )
            }
            if not {"code_items", "files", "code_item_kinds"}.issubset(tables):
                logger.warning(
                    "Browse.VC.db schema mismatch (missing tables): %s", db_path
                )
                return

            # Build kind id → name map
            for row in self._conn.execute("SELECT id, name FROM code_item_kinds"):
                self._kind_map[row[0]] = row[1]

            self._available = True
            count = self._conn.execute("SELECT COUNT(*) FROM code_items").fetchone()[0]
            logger.info("Browse.VC.db opened: %s (%s symbols)", db_path, f"{count:,}")
        except Exception as exc:
            logger.warning("Browse.VC.db unavailable (%s): %s", type(exc).__name__, exc)

    # ── Properties ────────────────────────────────────────────────────

    @property
    def available(self) -> bool:
        return self._available

    @property
    def db_path(self) -> Path:
        return self._db_path

    # ── Symbol Lookup ─────────────────────────────────────────────────

    def find_symbol(
        self,
        name: str,
        *,
        kinds: tuple[int, ...] | None = NAVIGABLE_KINDS,
        definitions_only: bool = True,
        limit: int = 50,
    ) -> list[dict]:
        """Find code items by exact name.

        Args:
            name: Symbol name (exact, case-sensitive match using the
                  ``ix_code_items_name`` index — typically ~1 ms).
            kinds: Restrict to these ``code_item_kinds.id`` values.
                   Pass *None* to search all kinds.
            definitions_only: If *True*, filter out forward declarations
                   (entries where ``start_line == end_line``).
            limit: Maximum results.

        Returns:
            List of dicts with keys: ``name``, ``kind``, ``kind_id``,
            ``file_path`` (absolute), ``start_line``, ``end_line``,
            ``parent_id``, ``type_sig``, ``source``.
        """
        if not self._available:
            return []

        sql = """
            SELECT ci.id, ci.name, ci.kind, f.name,
                   ci.start_line, ci.end_line, ci.parent_id, ci.type
            FROM code_items ci
            JOIN files f ON ci.file_id = f.id
            WHERE ci.name = ?
        """
        params: list = [name]

        if kinds:
            placeholders = ",".join("?" * len(kinds))
            sql += f" AND ci.kind IN ({placeholders})"
            params.extend(kinds)

        if definitions_only:
            sql += " AND ci.start_line != ci.end_line"

        sql += " LIMIT ?"
        params.append(limit)

        assert self._conn is not None  # guarded by _available check above
        try:
            return [
                {
                    "id": row[0],
                    "name": row[1],
                    "kind": self._kind_map.get(row[2], f"kind_{row[2]}"),
                    "kind_id": row[2],
                    "file_path": row[3],
                    "start_line": row[4],
                    "end_line": row[5],
                    "parent_id": row[6],
                    "type_sig": row[7],
                    "source": "browse_db",
                }
                for row in self._conn.execute(sql, params)
            ]
        except sqlite3.Error as exc:
            logger.warning("Browse.VC.db query failed: %s", exc)
            return []

    # ── Member Lookup ─────────────────────────────────────────────────

    def find_members(self, parent_id: int, *, limit: int = 200) -> list[dict]:
        """Find child code items of *parent_id* (e.g. class members).

        Uses the ``ix_code_items_parent_id`` index — typically ~2 ms.
        """
        if not self._available:
            return []
        assert self._conn is not None
        try:
            return [
                {
                    "name": row[0],
                    "kind": self._kind_map.get(row[1], f"kind_{row[1]}"),
                    "start_line": row[2],
                    "end_line": row[3],
                    "type_sig": row[4],
                }
                for row in self._conn.execute(
                    """
                    SELECT ci.name, ci.kind, ci.start_line, ci.end_line, ci.type
                    FROM code_items ci
                    WHERE ci.parent_id = ?
                    ORDER BY ci.start_line
                    LIMIT ?
                    """,
                    (parent_id, limit),
                )
            ]
        except sqlite3.Error:
            return []

    # ── Inheritance ───────────────────────────────────────────────────

    def find_base_classes(self, class_name: str) -> list[str]:
        """Return names of classes that *class_name* inherits from.

        Note: ``base_class_parents`` stores per-file entries, so querying
        by *name* across all entries is correct.
        """
        if not self._available:
            return []
        assert self._conn is not None
        try:
            rows = self._conn.execute(
                """
                SELECT DISTINCT ci_base.name
                FROM base_class_parents bcp
                JOIN code_items ci_derived ON bcp.parent_code_item_id = ci_derived.id
                JOIN code_items ci_base ON bcp.base_code_item_id = ci_base.id
                WHERE ci_derived.name = ?
                """,
                (class_name,),
            ).fetchall()
            return [r[0] for r in rows]
        except sqlite3.Error:
            return []

    def find_derived_classes(self, class_name: str, *, limit: int = 50) -> list[dict]:
        """Return classes that inherit from *class_name*."""
        if not self._available:
            return []
        assert self._conn is not None
        try:
            return [
                {"name": row[0], "file_path": row[1]}
                for row in self._conn.execute(
                    """
                    SELECT DISTINCT ci_derived.name, f.name
                    FROM base_class_parents bcp
                    JOIN code_items ci_base ON bcp.base_code_item_id = ci_base.id
                    JOIN code_items ci_derived ON bcp.parent_code_item_id = ci_derived.id
                    JOIN files f ON ci_derived.file_id = f.id
                    WHERE ci_base.name = ?
                    LIMIT ?
                    """,
                    (class_name, limit),
                )
            ]
        except sqlite3.Error:
            return []

    # ── Cleanup ───────────────────────────────────────────────────────

    def close(self) -> None:
        if self._conn:
            self._conn.close()
            self._conn = None
            self._available = False
